apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
      - name: brain-app
        image: 061039785879.dkr.ecr.eu-north-1.amazonaws.com/brain-ecr:react_image
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      
      - name: cloudwatch-agent
        image: amazon/cloudwatch-agent:latest
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: cwagent-config
          mountPath: /etc/cwagentconfig
      
      volumes:
      - name: nginx-logs
        emptyDir: {}
      - name: cwagent-config
        configMap:
          name: cwagent-config
