apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app-deployment
  labels:
    app: brain-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
        - name: brain-app
          image: 061039785879.dkr.ecr.eu-north-1.amazonaws.com/brain-ecr:react_image
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-logs
              mountPath: /var/log
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:latest
          command: ["/opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent"]
          args:
            - "-config"
            - "file:/etc/cwagentconfig/cloudwatch-agent-config.json"
          volumeMounts:
            - name: app-logs
              mountPath: /var/log
            - name: cwagent-config
              mountPath: /etc/cwagentconfig
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: cwagent-config
          configMap:
            name: cwagent-config

