apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app-deployment
  labels:
    app: brain-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
        - name: brain-app
          image: 061039785879.dkr.ecr.eu-north-1.amazonaws.com/brain-ecr:react_image
          ports:
            - containerPort: 3000

