apiVersion: v1
kind: Service
metadata:
  name: brain-app-service
spec:
  type: LoadBalancer
  selector:
    app: brain-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: alt
    port: 3000
    targetPort: 3000
