apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: default
data:
  cwagentconfig.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/app-logs/app.log",
                "log_group_name": "/aws/brain-tasks-app/app",
                "log_stream_name": "react-container-log",
                "timezone": "UTC"
              }
            ]
          }
        }
      }
    }

